version: "3.8"

services:
    web:
        image: nginx:latest
        ports:
          - 80:80
        depends_on:
          - api

    api:
        build: .
        environment:
          - PORT=8080
        ports:
          - 8080:8080